#!/bin/sh

. /etc/phitv/scripts.conf

clear
prompt="Select one:"
options=("List Domain" "Add Domain" "Delete Domain" "Change Pass VPS" "Change Port Admin" "Chmod Webserver" "Update Nginx, PHP, MariaDB") # End Options

printf "=========================================================================\n"
printf "                          Script v$phitv_version \n"
printf "=========================================================================\n"
printf "                             Menu\n"
printf "=========================================================================\n"
PS3="
$prompt"
select opt in "${options[@]}" "Exit"; do 

    case "$REPLY" in
	    1 ) /etc/phitv/menu/liet-ke-domain;;
	    2 ) /etc/phitv/menu/them-domain;;
	    3 ) /etc/phitv/menu/xoa-domain;;
	    4 ) /etc/phitv/menu/doi-pass-vps;;
	    5 ) /etc/phitv/menu/doi-port-admin;;
	    6 ) /etc/phitv/menu/phan-quyen-webserver;;
		7 ) /etc/phitv/menu/update-nginx-php-mariadb;;
	    # End Menu

	    $(( ${#options[@]}+1 )) ) printf "\nGoodbye!\n\n"; break;;
	    *) echo "Wrong select";continue;;

    esac

done